name: seedscan
description: SeedScan - AI-powered tree plantation app
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & fonts
  google_fonts: ^5.0.0
  lucide_icons: ^0.257.0


  # State management
  provider: ^6.0.5

  # Camera / scanning & image
  mobile_scanner: ^7.1.3
  image_picker: ^1.1.0

  # Utilities
  flutter_svg: ^1.1.6
  intl: ^0.18.0
  badges: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
assets:
    - assets/images

