name: seedscan
description: SeedScan - AI-powered tree plantation app
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Model
  tflite_flutter: ^0.11.0  

  # UI & fonts
  google_fonts: ^5.0.0
  lucide_icons: ^0.257.0
  # icons_launcher: ^3.0.3


  # State management
  provider: ^6.0.5

  # Camera / scanning & image
  mobile_scanner: ^7.1.3
  camera: ^0.10.5+5
  image_picker: ^1.1.0
  image: ^4.0.0
  path_provider: ^2.1.0

  # Location services
  geolocator: ^10.1.0
  permission_handler: ^11.0.1

  # Utilities
  flutter_svg: ^1.1.6
  intl: ^0.18.0
  badges: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/

# icons_launcher:
#   image_path: "assets/images/logo.png"
#   platforms:
#     android:
#       enable: true
#     ios:
#       enable: true

